from __future__ import annotations

import json
import logging
from typing import AsyncIterator, List

from app.services.chat_v2.schemas import ToolResult
from app.services.chat_v2.streaming import sse_tool_start, sse_tool_result

logger = logging.getLogger(__name__)

async def execute(
    query: str,
    user_id: str,
    notebook_id: str,
    session_id: str,
    material_ids: List[str] = None,
    step_index: Optional[int] = None,
) -> AsyncIterator[str | ToolResult]:
    yield sse_tool_start("research", label="Starting deep research…")

    try:
        from app.services.research.pipeline import stream_research

        full_response: List[str] = []
        citations: list = []
        pdf_info: dict = {}

        async for event in stream_research(
            query=query,
            user_id=user_id,
            notebook_id=notebook_id,
            session_id=session_id,
            material_ids=material_ids,
        ):
            yield event

            if isinstance(event, str):
                if "token" in event and "data:" in event:
                    for line in event.split("\n"):
                        line = line.strip()
                        if line.startswith("data:"):
                            raw = line[5:].strip()
                            try:
                                payload = json.loads(raw)
                                content = payload.get("content", "")
                                if content:
                                    full_response.append(content)
                            except json.JSONDecodeError:
                                pass
                elif "citations" in event and "data:" in event:
                    for line in event.split("\n"):
                        line = line.strip()
                        if line.startswith("data:"):
                            raw = line[5:].strip()
                            try:
                                payload = json.loads(raw)
                                citations = payload.get("citations", [])
                            except json.JSONDecodeError:
                                pass
                elif "research_pdf" in event and "data:" in event:
                    for line in event.split("\n"):
                        line = line.strip()
                        if line.startswith("data:"):
                            raw = line[5:].strip()
                            try:
                                pdf_info = json.loads(raw)
                            except json.JSONDecodeError:
                                pass

        complete = "".join(full_response)
        
        # Append PDF download link if available
        if pdf_info and "url" in pdf_info:
            download_link = (
                f"\n\n---\n"
                f"### [📄 Download Research PDF Report]({pdf_info['url']})\n"
                f"*Generated by Kepler Intelligence Engine*"
            )
            complete += download_link

        if not complete:
            logger.warning("Research tool produced empty response — possible streaming format mismatch")

        yield sse_tool_result("research", success=True, summary=f"Research complete — {len(citations)} sources", step_index=step_index)

        yield ToolResult(
            tool_name="research",
            success=bool(complete),
            content=complete or "Research completed but no text was captured.",
            metadata={
                "intent": "WEB_RESEARCH", 
                "sources_count": len(citations), 
                "citations": citations,
                "pdf": pdf_info
            },
        )


    except Exception as exc:
        logger.error("Research pipeline failed: %s", exc)
        yield sse_tool_result("research", success=False, summary="Research failed", step_index=step_index)
        yield ToolResult(
            tool_name="research",
            success=False,
            content="",
            metadata={"error": str(exc)},
        )
